### ISSUE TITLE
Formatting of size looks odd on Windows

### ISSUE THREAD

**Issue by user1823** [Aleks-Ya/note-size-anki-addon#1]
<img width=500 src="https://github.com/Aleks-Ya/note-size-anki-addon/assets/92206575/202e30b6-9e35-4646-ad6e-acc7e4486104">

**Comment by Aleks-Ya** [comment]
I don't have experience in design, so I just used default fonts here. 
Sizes (e.g. `322B`) are formatted mono-spaced to make them stand out from the rest of the text.
Could you explain what exactly you'd change in the formatting?

**Comment by user1823** [comment]
In the following image, the file sizes are displayed better IMO.

<img src="https://raw.githubusercontent.com/Aleks-Ya/note-size-anki-addon/main/description/column_shown.png">

On Windows, KB appears smaller than the numbers, which appears odd.

Regarding the use of monospaced fonts, I want to mention that Qt (the toolkit used by Anki) defaults to Courier for monospaced font on Windows despite a much better font (Consolas) being available on practically all versions of Windows. To overcome this, you may want to use an approach similar to Anki.

https://github.com/ankitects/anki/blob/33a923797afc9655c3b4f79847e1705a1f998d03/qt/aqt/addons.py#L1585-L1587

https://github.com/ankitects/anki/blob/33a923797afc9655c3b4f79847e1705a1f998d03/ts/editor/CodeMirror.svelte#L107

**Comment by Aleks-Ya** [comment]
Hi @user1823 , I applied `Consolas` font on Windows. Does it look ok now (it's not published yet):
![image](https://github.com/Aleks-Ya/note-size-anki-addon/assets/4932373/3f400e65-8632-4e34-9358-acfc36cff496)

**Comment by user1823** [comment]
Yes, looks better now.

**Comment by Aleks-Ya** [comment]
Fixed in release [1.7.0](https://github.com/Aleks-Ya/note-size-anki-addon/releases/tag/v1.7.0)
