### ISSUE TITLE
The new update broke the addon

### ISSUE THREAD

**Issue by LuizMarchi** [Aleks-Ya/note-size-anki-addon#2]
Anki encountered a problem. Please follow the troubleshooting steps.
Add-ons possibly involved: ⁨Note Size - sort notes by size⁩

Anki 24.06.2 (33a92379)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.main", line 636, in loadCollection
  File "_aqt.hooks", line 1593, in __call__
  File "C:\Users\luizm\AppData\Roaming\Anki2\addons21\1188705668\__init__.py", line 46, in __initialize
    log: Logger = __configure_logging(mw.addonManager, module)
  File "C:\Users\luizm\AppData\Roaming\Anki2\addons21\1188705668\__init__.py", line 25, in __configure_logging
    log_dir.mkdir(exist_ok=True)
  File "pathlib", line 1323, in mkdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\luizm\\AppData\\Roaming\\Anki2\\logs\\addons\\1188705668'
===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Browser Play Button ['182970692', 2023-11-02T23:39, 'None', '']
AJT Card Management ['1021636467', 2024-03-15T22:51, 'None', '']
Add Table ['1237621971', 2023-06-18T08:37, 'None', '']
Allows empty first field during adding and import ['46741504', 2021-10-17T18:27, 'None', '']
AnkiDraw - Draw and write using mouse and stylus with pressure support ['1868980340', 2024-04-04T15:20, 'None', '']
AnkiWebView Inspector ['31746032', 2023-06-27T16:26, 'None', '']
Auto Highlight Cloze in Browser Fork by Shige ['210078606', 2024-06-12T08:44, 'None', mod]
Batch Editing ['291119185', 2023-10-25T21:38, 'None', '']
Browser Card Info Bar ['2140680811', 2024-04-05T07:39, 'None', mod]
CSS Injector - Change default editor styles ['181103283', 2023-02-21T18:15, 'None', '']
Clickable note links ['1170639320', 2024-05-30T13:18, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T12:06, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T22:19, 'None', mod]
Deck Browser CSS ['153779542', 2024-03-27T19:30, 'None', '']
Disconnected Review-Log Cleaner ['1067771610', 2023-08-19T10:41, 'None', '']
Editor auto show or hide during review Created by Shige ['1715279230', 2024-03-23T12:51, 'None', mod]
Filtered Deck From Tag ['2058067048', 2023-02-18T22:42, 'None', '']
Force full sync button ['1269480121', 2020-07-20T21:48, 'None', '']
Forvo Pronunciation Downloader Fixed by Shige ['1784714388', 2024-03-01T01:04, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-21T16:17, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-06-01T11:02, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T04:15, 'None', '']
Japanese Pitch Accent ['148002038', 2023-05-07T10:01, 'None', '']
JapaneseFurigana ['678316993', 2024-02-12T11:06, 'None', mod]
More Flags - Add card flags with custom names and colors ['146757953', 2023-10-17T06:14, 'None', mod]
Multi Deck Importer Fixed by Shige ['1563006742', 2024-02-16T21:33, 'None', '']
Note Size - sort notes by size ['1188705668', 2024-06-23T06:24, 'v1.10.0', '']
Open linked pdf docx epub audiovideo etc in external Program win linux ['879473266', 2024-04-09T18:56, 'None', mod]
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2024-06-03T22:56, 'None', '']
Paste Images As WebP ['1151815987', 2024-04-23T07:42, 'None', mod]
Quick tagging 21 ['304770511', 2020-02-11T03:17, 'None', mod]
Remove card history ['2089200096', 2023-10-19T00:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
Spell Checker ['369581638', 2023-10-11T10:47, 'None', '']
Syllabus - Anki Statistics and Export by Tag and Deck Fixed by Shige ['1403834620', 2024-05-29T08:53, 'None', mod]
Symbols As You Type ['2040501954', 2024-01-20T02:42, 'None', '']
True Retention ['613684242', 2017-11-19T17:43, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T16:28, 'None', mod]
Zoom24 - Keep zoom level after reboot Fixed by Shige ['1923741581', 2024-05-01T22:23, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T13:22, 'None', '']

===IDs of active AnkiWeb add-ons===
1021636467 1067771610 111623432 1151815987 1170639320 1188705668 1210908941 1237621971 1269480121 1374772155 1403834620 146757953 148002038 153779542 1563006742 1715279230 1771074083 1784714388 181103283 182970692 1868980340 1923741581 2040501954 2058067048 2089200096 210078606 2140680811 225180905 291119185 304770511 31746032 369581638 46741504 561945101 594329229 613684242 678316993 864545277 876946123 879473266

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Japanese ['1344485230', 2024-06-16T20:12, 'None', mod]
AJT Mortician ['1255924302', 2023-11-02T23:51, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T11:34, 'None', '']
Almost Mandatory Tags ['1386232247', 2022-12-28T14:51, 'None', '']
Anki Word Frequency ['110659003', 2024-03-25T06:44, 'None', mod]
AnkiPet - gamify your learning by caring for a pet Fixed by Shige ['2026040256', 2024-06-16T03:21, 'None', mod]
AnkiRestart - Quick Aniki Rebooter for Customize  Develop Created by Shige ['237169833', 2024-02-06T10:21, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-06-01T11:05, 'None', '']
BetterSearch ['1052724801', 2024-03-06T13:25, 'None', '']
Browser Search By Word Count ['307706071', 2023-10-10T20:13, 'None', '']
Clickable Tags v20 original ['380714095', 2022-01-30T19:58, 'None', '']
Deck icons ['1519592143', 2024-05-30T09:30, 'None', '']
Display total cards and time studied on main screen ['352950969', 2023-01-30T16:24, 'None', '']
Edit Field During Review ['1020366288', 2022-08-29T16:38, 'None', '']
Editor Live Preview ['1960039667', 2024-03-04T20:59, 'None', '']
Extra stats in the Deck Browser ['93718002', 2021-02-21T05:19, 'None', '']
Google Translate ['1536291224', 2024-05-08T11:16, 'None', mod]
Kanji Colorizer stroke order diagrams ['1964372878', 2024-01-08T14:48, 'None', mod]
Kanji Grid ['909972618', 2019-01-09T19:40, 'None', '']
Kanji Table ['1828617820', 2024-01-11T18:19, 'None', '']
Leech Toolkit - Advanced leech tag management Fixed by Shige ['1633380637', 2024-02-21T04:33, 'None', '']
Open deck in browser from main window ['1886315955', 2019-10-08T12:00, 'None', '']
Readable Addons Folder - for Addons Development Fork by Shige ['158759867', 2024-04-09T03:55, 'None', '']
Remaining time for Anki 21 ['1508357010', 2024-04-15T23:15, '24.4.16i24', '']
Reset Card Scheduling Fixed by Shige ['83793850', 2024-01-17T02:46, 'None', '']
Search Stats Extended ['1613056169', 2024-03-28T20:05, 'None', '']
Show number of results in browser ['917646119', 2021-03-24T17:55, 'None', '']
Trigger and actions - Change card based on another Fixed by Shige ['119880939', 2024-04-17T08:52, 'None', '']
VOICEVOX Japanese Text To Speech Audio Generator ['366960193', 2024-04-09T19:07, 'None', mod]

**Comment by Aleks-Ya** [comment]
Hi @LuizMarchi , thanks for reporting
This problem was fixed in [v1.11.0](https://github.com/Aleks-Ya/note-size-anki-addon/releases/tag/v1.11.0).
Please, check it out
